redis:
  image: index.alauda.cn/library/redis:latest
  ports:
  - '6379'
web:
  command: python app.py
  image: index.alauda.cn/alauda/flask-redis:latest
  links:
  - redis:redis
  ports:
  - '80/http'